Add support for oscillation limit angles to fans
JeffSteinbok/hass-dreo pull request #115
Opened 2024-06-01 15:14 UTC by MalteMatthey

This update adds support for oscillation limit angles to fans (issue #107) by introducing four new entities to control angle limits in all four directions.

Here are some things to consider:

- My fan (DR-HAF003S) requires a minimum of 30° between the top and bottom angles (and left and right) to oscillate. If this requirement is ignored, HomeAssistant will raise a ValueError. I hardcoded this 30° limit, but I'm unsure if it's appropriate for all fans.
- I didn't include the 30° difference in the range of the numbers. I thought it would be more intuitive to have both vertical and both horizontal angles in the same range, even though you can't set the horizontal left angle to less than -30°, for example. Feel free to adjust this.
- Dreo released several new fans, each with different supported angles (see issue #106). I hardcoded the limit angles, so if you fix the issue, you will need to set them accordingly.
- Adding four new numbers crowds the device control a bit, but I couldn't think of a better alternative. Implementing it like the oscillation angles for heaters could work, but it doesn't allow for exact and asymmetric controls.

Thanks again for the excellent integration!

2024-07-04 03:10 UTC, JeffSteinbok requested changes
You've confirmed that this doesn't expose these attributes to fans that shouldn't have them?

2024-07-04 03:10 UTC, JeffSteinbok commented on custom_components/dreo/pydreo/pydreofan.py
> +            if value - bottom_angle < 30:
Please move into a constant

2024-07-04 10:07 UTC, MalteMatthey commented
Sorry, moved the minimum difference in a constant now.

Unfortunatly, I can't confirm that these attributes aren't exposed to fans, that shouldn't have them.

Every fan that allows setting the horizontal angle should also support setting the oscillation limits, and similarly, every fan that allows setting the vertical angle should support setting the vertical oscillation limits.

I don't have a fan that doesn't support vertical oscillation that I can test on.

I have some problems understanding the confirmation process for adding the numbers. Can you help me understand, what exactly `add_entries` https://github.com/JeffSteinbok/hass-dreo/blob/1874bcdb0d83eb2fbb3c953ae0442bc98ef50739/custom_components/dreo/number.py#L66-L90 and the called `is_feature_supported` https://github.com/JeffSteinbok/hass-dreo/blob/1874bcdb0d83eb2fbb3c953ae0442bc98ef50739/custom_components/dreo/pydreo/pydreobasedevice.py#L196-L206 does in this context?

I don't quite understand how this confirms which numbers need to be added, and unfortunatly I don't have the time to dive deeper into the project right now. It would be great if you could help me with that!

2024-07-06 15:17 UTC, JeffSteinbok approved these changes

2024-08-05 03:12 UTC, merged